config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :users do
    collection do
      get :sign_in
      post :sign_in
    end
  end
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize

  private

  def authorize
    return if action_name == 'sign_in'
    redirect_to sign_in_users_path unless sign_in?
  end

  def sign_in?
    session[:current_user].present?
  end

  def current_user
    @current_user ||= User.new(session[:current_user])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    event = RestClient.get "https://sb-api.tes.co.jp/api/v1/event/#{params[:id]}", current_user.request_headers
    @event = Responses::Event.value_of(JSON.parse(event))
    p @event
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    events = RestClient.get 'https://sb-api.tes.co.jp/api/v1/event?limit=5&order=desc', current_user.request_headers

    events = JSON.parse(events.body)
    @events = events.map { |event| Responses::Event.value_of(event) }
  end

  def sample
  end
end

app/controllers/sample_controller.rb
class SampleController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_in
    unless request.post?
      @user = User.new
      return
    end

    begin
      @user = User.new(user_params)
      response = RestClient.post 'https://sb-api.tes.co.jp/api/v1/auth/sign_in', @user.authorize_params

      if response.code == 200
        header = Responses::SignIn::Header.new(response.headers)
        p JSON.parse(response.body)
        body = Responses::SignIn::Body.new(JSON.parse(response.body)['data'])

        session[:current_user] = User.new(
          name: body.name,
          email: body.email,
          id: body.id,
          access_token: header.access_token,
          client: header.client,
          uid: body.uid
        )
        redirect_to root_path
      end
    rescue RestClient::ExceptionWithResponse => e
      @response_body = JSON.parse(e.response.body)
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/show.html.slim
= @event.id
br
= @event.name
br
= link_to 'home', root_path

app/views/home/index.html.slim
.main.col-md-12
  .row
    .col-lg-6
      .card.dashboard-card.dashboard-area
        .card-header 新着イベント
        .list-group.list-group-flush
          - @events.each do |event|
            = link_to event.name, event_path(id: event.id), class: 'list-group-item list-group-item-action clearfix'

app/views/home/sample.html.erb
<a href='/'>hoge</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SbFrontRailsSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="turbolinks-cache-control" content="no-cache">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sample/index.html.erb
<a href='/'>hoge</a>

app/views/users/sign_in.html.slim
.container
  .row
    .col-md-4
    .col-md-4
      .login-panel
      - if @response_body.present?
        .alert.alert-danger.error-message role="alert"
          - @response_body['errors'].each do |error|
            p = error
      .panel.panel-default
        = form_for(@user, url: { action: 'sign_in' }) do |f|
          h2.form-signin-heading loungeek
          label.sr-only for="inputLoginId"  アカウント
          = f.text_field :email, class: 'form-control', autofocus: '', required: true, placeholder: 'email'
          label.sr-only for="inputPassword"  Password
          = f.password_field :password, class: 'form-control', required: true, placeholder: 'password'
          = f.submit 'サインイン', class: 'btn btn-lg btn-primary btn-block'